version: 1

project:
  root: .
  build_config: lzc-build.yml
  package_file: package.yml
  output: .lazycat-build/backapp.lpk
  target_arch: amd64

update:
  strategy: publish
  allow_downgrade: false
  version_source:
    type: image
    image: backapp
    bump: patch
build:
  run_buildscript: false
images:
  - id: backapp
    target: service
    service: backapp
    source: ghcr.io/dennis960/backapp
    channel: custom
    sort: created
    tag_regex: '^latest$'
    delivery:
      mode: lazycat
stores:
  official:
    enabled: true
    skip_if_version_exists: true
    changelog_locales: [zh, en]
  private:
    enabled: true
    skip_if_version_exists: true
    name: BackApp
    summary: "UI for Backup automation over SSH, replacing custom shell scripts and cron configurations"
