application:
  subdomain: backapp
  upstreams:
    - location: /
      backend: http://backapp:8080/
services:
  backapp:
    # upstream: ghcr.io/dennis960/backapp:latest@sha256:39194b52341a04f6a7127e0b153c76d3abe51d7a32dc23de932f0ba528dac6bc
    image: registry.lazycat.cloud/czyt/dennis960/backapp:83d8daa7c2d9e739
    restart: unless-stopped
    healthcheck:
      test:
        - CMD-SHELL
        - wget -qO- http://localhost:8080/health || exit 1
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
    binds:
      - /lzcapp/var/backapp-data:/data
      - /lzcapp/var/backups/app:/var/backups/app
      - /lzcapp/var/backups/archive:/var/backups/archive
    cpu_shares: 512
    mem_limit: 512M
    entrypoint: sh -c "cd /data &&exec /app/app -port=8080"
